### ISSUE TITLE
[Cloud Support] AWS ECS Reconfirmation and Documentation

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#435]
### Tasks

- [x] Confirm deployment of latest application
  - #420 

- Documentation
  - [x] AWS Environment Setup Procedure
  - [x] Application Deployment Procedure to AWS Environment
