### ISSUE TITLE
[Cloud Support] Setup development environment

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#453]
### Tasks

- [x] Setup development environment
- [x] Confirm application specs
- [x] Run Test cases

### Documents

- Environment Setup Procedure
  - https://drive.google.com/file/d/1tJVsgJIaFn-oHSeTgKLSETIaoFmt-BBf/view?usp=drive_link
- Spec Documents
  - https://docs.google.com/presentation/d/1slp8oZSuriSWArkrQKrMnY9SLHw4bOgL/edit?usp=drive_link&ouid=104622411264052056363&rtpof=true&sd=true
  - https://drive.google.com/drive/folders/1l02DPAEBgSkUA9aMggm1ZcwA-oNC82W3
- Testcase
  - https://drive.google.com/drive/folders/1CSBbJlL4vIaWJDoS5IyCWjz6Rv0a-bKO
    - https://docs.google.com/spreadsheets/d/1fUhTeTXKgfpRP_Nqs-OB2o5mzE1aXu-H/

### Related

- #422
